FROM node:16-alpine as build
RUN ls
WORKDIR /usr/server
COPY . .
RUN apk add --no-cache python3 \
        make \
        g++ 
RUN npm ci
FROM node:16-alpine
COPY --from=build /usr/server /usr/server
WORKDIR /usr/server/backend
CMD node server.js
