version: "3.8"
services:
  db:
    image: "postgres:11"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    links:
      - db
volumes:
  pgdata:
